### ISSUE TITLE
KeyError: 'nuScenesMapDataset is not in the dataset registry'

### ISSUE THREAD

**Issue by canteen-man** [Tsinghua-MARS-Lab/neural_map_prior#14]
你好，我的安装版本是：
mmcv.1.3.14
执行python test.py ./project/configs/bevformer_30m_60m.py ./ckpts/bevformer_epoch_24.pth --eval iou
报错：
KeyError: 'nuScenesMapDataset is not in the dataset registry'
我debug到是envs/npn/lib/python3.8/site-packages/mmcv/utils/registry.py内
  obj_cls = registry.get(obj_type)
  if obj_cls is None:
      raise KeyError(
          f'{obj_type} is not in the {registry.name} registry')

这里的registry.get(obj_type)返回为空。
谢谢

**Comment by abbyxxn** [comment]
It seems that the issue is occurring because you have not registered the plugin in your tool/train.py. You can refer to [this](https://github.com/Tsinghua-MARS-Lab/neural_map_prior/blob/e0a8188a40e7a701b8c355b3c90c758310557998/tools/train.py#L109) for guidance.

**Comment by LIvanoff** [comment]
I can't import the module

python3 tools/test.py ./project/configs/our_cfg.py  ./npm_epoch_24.pth --eval iou

project.neural_map_prior
Traceback (most recent call last):
  File "tools/test.py", line 269, in <module>
    main()
  File "tools/test.py", line 146, in main
    plg_lib = importlib.import_module(_module_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'project'
