### ISSUE TITLE
Versions of some dependent libraries during environment configuration

### ISSUE THREAD

**Issue by SherLockLi99** [Tsinghua-MARS-Lab/neural_map_prior#19]
Hello!I would like to know why I get the following error when I configure my environment according to the official requirements, is it the version of some of my dependent libraries?

`Traceback (most recent call last):
  File "./tools/test.py", line 7, in <module>
    import mmcv
  File "/home/hwt/anaconda3/envs/npn/lib/python3.8/site-packages/mmcv/__init__.py", line 5, in <module>
    from .image import *
  File "/home/hwt/anaconda3/envs/npn/lib/python3.8/site-packages/mmcv/image/__init__.py", line 5, in <module>
    from .geometric import (cutout, imcrop, imflip, imflip_, impad,
  File "/home/hwt/anaconda3/envs/npn/lib/python3.8/site-packages/mmcv/image/geometric.py", line 8, in <module>
    from .io import imread_backend
  File "/home/hwt/anaconda3/envs/npn/lib/python3.8/site-packages/mmcv/image/io.py", line 19, in <module>
    from PIL import Image, ImageOps
  File "/home/hwt/anaconda3/envs/npn/lib/python3.8/site-packages/PIL/Image.py", line 68, in <module>
    from ._typing import StrOrBytesPath, TypeGuard
  File "/home/hwt/anaconda3/envs/npn/lib/python3.8/site-packages/PIL/_typing.py", line 10, in <module>
    NumpyArray = npt.NDArray[Any]
AttributeError: module 'numpy.typing' has no attribute 'NDArray'`

**Comment by abbyxxn** [comment]
I have encountered this error before, but I don't remember how to fix it. Perhaps you could try changing the version of numpy.

**Comment by SherLockLi99** [comment]
Thank you! I have resolved this issue. It seemed to be caused by the version of mmdet3d being too high. When I adjusted the version to MMDetection3D==v0.17.2, the problem was solved!
