### ISSUE TITLE
'NeuralMapPrior is not in the models registry'

### ISSUE THREAD

**Issue by takeshie** [Tsinghua-MARS-Lab/neural_map_prior#2]
hi does anyone konow how to slove this problem?

2023-07-07 23:02:23,832 - mmdet - INFO - Set random seed to 0, deterministic: False
Traceback (most recent call last):
  File "tools/train.py", line 280, in <module>
    main()
  File "tools/train.py", line 207, in main
    model = build_model(
  File "/home/users/hao.yetian/test/neural_map_prior-main/mmdetection3d/mmdet3d/models/builder.py", line 84, in build_model
    return build_detector(cfg, train_cfg=train_cfg, test_cfg=test_cfg)
  File "/home/users/hao.yetian/test/neural_map_prior-main/mmdetection3d/mmdet3d/models/builder.py", line 57, in build_detector
    return DETECTORS.build(
  File "/home/users/hao.yetian/miniconda3/envs/npn/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/users/hao.yetian/miniconda3/envs/npn/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/users/hao.yetian/miniconda3/envs/npn/lib/python3.8/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    raise KeyError(
KeyError: 'NeuralMapPrior is not in the models registry'

**Comment by abbyxxn** [comment]
NeuralMapPrior is registered by MAPPERS, and there are two ways to solve it.
1. change MAPPERS to DETECTORS in [project/neural_map_prior/models/mapers/original_hdmapnet.py](https://github.com/Tsinghua-MARS-Lab/neural_map_prior/blob/1b22f5f98f7c33773eebb5889958a5ac1ab688eb/project/neural_map_prior/models/mapers/original_hdmapnet.py#L13

2. or add follow in mmdet3d/models/builder.py
```
    MAPPERS = Registry('mappers')
    def build_mapper(cfg, train_cfg=None, test_cfg=None):
       if train_cfg is not None or test_cfg is not None:
           warnings.warn(
                'train_cfg and test_cfg is deprecated, '
                'please specify them in model', UserWarning)
       return MAPPERS.build(cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))

```
replace line 84 ```return build_detector(cfg, train_cfg=train_cfg, test_cfg=test_cfg)``` by 
```return build_mapper(cfg, train_cfg=train_cfg, test_cfg=test_cfg)```

**Comment by takeshie** [comment]
@abbyxxn thank you for your responds ,and could you give me the permission for the **”nuScences_map_trainval_infos_train.pkl” ， “nuScences_map_trainval_infos_val.pkl” and ResNet101 pretrain file "r101_dcn_fcos3d_pretrain.pth "**?I can't get these file without your agreement. my email is 61330037@qq.com
thank you again for the nice work!

**Comment by abbyxxn** [comment]
Can you try this new link [nuScences_map_trainval_infos_train.pkl](https://drive.google.com/file/d/18P8LZcEVxGYAvMQpEROrF0pnpu62ffvD/view?usp=sharing), [nuScences_map_trainval_infos_val.pkl](https://drive.google.com/file/d/1H6HfnNqmKBFvNIivApcsRUCgPtxgIq7A/view?usp=sharing) and [r101_dcn_fcos3d_pretrain.pth](https://drive.google.com/file/d/1bkiDxA97XvhnRQnGB44ol3xwhVjGcffu/view?usp=sharing) ?

**Comment by takeshie** [comment]
> 

yes,new link is fine

**Comment by takeshie** [comment]
@abbyxxn Hi, I find there are many dataset adress are fixed. I fix most of them but still get a dataset error like this,I don't find the path to replace this with correct path:
**I find out that error is becasue the train.pkl is generated by author's adress instead of mine.**
```
Traceback (most recent call last):
  File "tools/train.py", line 280, in <module>
    main()
  File "tools/train.py", line 269, in main
    train_model(
  File "/home/users/hao.yetian/test/neural_map_prior-main/mmdetection3d/mmdet3d/apis/train.py", line 28, in train_model
    train_detector(
  File "/home/users/hao.yetian/miniconda3/envs/npn/lib/python3.8/site-packages/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/users/hao.yetian/miniconda3/envs/npn/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/users/hao.yetian/miniconda3/envs/npn/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/users/hao.yetian/miniconda3/envs/npn/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/users/hao.yetian/miniconda3/envs/npn/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/users/hao.yetian/miniconda3/envs/npn/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/users/hao.yetian/miniconda3/envs/npn/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/users/hao.yetian/miniconda3/envs/npn/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/users/hao.yetian/miniconda3/envs/npn/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/users/hao.yetian/miniconda3/envs/npn/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/users/hao.yetian/test/neural_map_prior-main/project/neural_map_prior/datasets/nuscenes_dataset.py", line 228, in __getitem__
    data = self.prepare_train_data(idx)
  File "/home/users/hao.yetian/test/neural_map_prior-main/project/neural_map_prior/datasets/base_dataset.py", line 160, in prepare_train_data
    example = self.pipeline(input_dict)
  File "/home/users/hao.yetian/miniconda3/envs/npn/lib/python3.8/site-packages/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/home/users/hao.yetian/test/neural_map_prior-main/project/neural_map_prior/datasets/pipelines/loading.py", line 41, in __call__
    img = [mmcv.imread(name, self.color_type) for name in filename]
  File "/home/users/hao.yetian/test/neural_map_prior-main/project/neural_map_prior/datasets/pipelines/loading.py", line 41, in <listcomp>
    img = [mmcv.imread(name, self.color_type) for name in filename]
  File "/home/users/hao.yetian/miniconda3/envs/npn/lib/python3.8/site-packages/mmcv/image/io.py", line 176, in imread
    check_file_exist(img_or_path,
  File "/home/users/hao.yetian/miniconda3/envs/npn/lib/python3.8/site-packages/mmcv/utils/path.py", line 23, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: img file does not exist: /public/MARS/datasets/nuScenes/samples/CAM_FRONT
```/n008-2018-08-06-15-06-32-0400__CAM_FRONT__1533583194162404.jpg

**Comment by abbyxxn** [comment]
Thank you for your kind reminder. I will replace the path with a relative path in the repo on these days. If you want to run the repo quickly, this is an option to solve by changing the base path here. https://github.com/Tsinghua-MARS-Lab/neural_map_prior/blob/b930dfdfccdb3b95263f75542a82e54e30db768d/project/neural_map_prior/datasets/pipelines/loading.py#L40, maybe that can help you. In the future, I will consider replacing the absolute path in info.pkl.

**Comment by takeshie** [comment]
@abbyxxn above all is done! finally I come to the visualization process.I find we lack of the file named **'_infos_cityname.pkl'** with this code in lane_render.py:
```
def load_nusc_data_cities(dataset, root=None):
    if root is None:
        root = '/home/xiongx/repository/marsmap/global_map_construction'
    with open(f'{root}/{dataset}_infos_cityname.pkl', 'rb') as f:
        data_city_names = pkl.load(f)
    print(f'load {len(data_city_names)} {dataset} city names for nuscenes dataset...')
    return data_city_names
```
do you know how to get this file or generate this?

**Comment by abbyxxn** [comment]
I have uploaded [train_city_infos.pkl](https://drive.google.com/file/d/1WZ9fzVIiq9V-B8_l3EtF19Q9aLg6hmPG/view?usp=sharing) and [val_city_infos.pkl](https://drive.google.com/file/d/1J3-BQzbaKJaHsEMZTTVDq5JvO5HHG41M/view?usp=sharing) and add in [data_prep](https://github.com/Tsinghua-MARS-Lab/neural_map_prior/blob/main/docs/data_preparation.md) last night. Please download and change the name to train_infos_cityname.pkl and val_infos_cityname.pkl.﻿

**Comment by takeshie** [comment]
@abbyxxn hi~here still a little question here is still like something are missing in files '**lane_render.py**'.do you know how to set the dataset root and get this data which are bound in '*',code as follows:
I try to skip them and get a blank picture
```
        ***********************
        result_root_gt = '/home/xiongx/repository/marsmap/vis_results/GT'
        bev_feature_gt = torch.load(os.path.join(result_root_gt, info['token'])).astype(np.int32)
        result_root_baseline = '/home/xiongx/repository/marsmap/vis_results/bevformer_baseline'
        bev_feature_baseline = torch.load(os.path.join(result_root_baseline, info['token'])).astype(np.int32)

        result_root_hdmapnet = '/home/xiongx/repository/marsmap/vis_results/hdmapnet_baseline'
        bev_feature_hdmapnet = torch.load(os.path.join(result_root_hdmapnet, info['token'])).astype(np.int32)
        ***********************

        fig = plt.figure(figsize=(4, 8), dpi=200)
        row_num = 4
        for i, semantic_pro in enumerate([bev_feature_hdmapnet, bev_feature_baseline, bev_feature_org, bev_feature_gt]):
            ax = fig.add_subplot(row_num, 1, i + 1)
            semantic_show = np.full(
                shape=(3, semantic_pro.shape[-2],
                       semantic_pro.shape[-1]),
                fill_value=255, dtype=np.uint8)

            semantic_show[:, semantic_pro[2].astype(np.int32) == 1] = \
                np.array([107, 156, 123], dtype=np.uint8).reshape(3, 1)
            if i == 5:
                semantic_show[:, semantic_pro[0].astype(np.int32) == 1] = \
                    np.array([178, 97, 103], dtype=np.uint8).reshape(3, 1)
                semantic_show[:, semantic_pro[1].astype(np.int32) == 1] = \
                    np.array([97, 135, 178], dtype=np.uint8).reshape(3, 1)
            else:
                semantic_show[:, semantic_pro[0].astype(np.int32) == 1] = \
                    np.array([97, 135, 178], dtype=np.uint8).reshape(3, 1)
                semantic_show[:, semantic_pro[1].astype(np.int32) == 1] = \
                    np.array([178, 97, 103], dtype=np.uint8).reshape(3, 1)

            ax.imshow(semantic_show.transpose((1, 2, 0)))
            ax.set_xbound(0, 400)
            ax.set_ybound(0, 200)
            ax.axis('off')
```

**Comment by abbyxxn** [comment]
Hi, `lane_render.py` can be used to predict maps as input and output the global map through map tiles. You can try to download nmp_results.zip [here](https://drive.google.com/file/d/1vcajqEPfIJ_Vb4jrG4umoKY_qp3ZrsCE/view?usp=sharing), and put them together to form a global map. The code in '\*' is for comparing local map results, which can be skipped. I have refactored the [`lane_render.py`](https://github.com/Tsinghua-MARS-Lab/neural_map_prior/blob/main/project/neural_map_prior/map_tiles/lane_render.py) script and removed the '*' character; this should prevent you from encountering the previous error.

**Comment by takeshie** [comment]
@abbyxxn hi~could you please give me a guide about how to do the ablation w/o map prior? I want to check this
